
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.2.01 EDK_Im_Sp1.3
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

/* Definitions for driver PLBARB */
#define XPAR_XPLBARB_NUM_INSTANCES 1

/* Definitions for peripheral PLB */
#define XPAR_PLB_BASEADDR 0x00000000
#define XPAR_PLB_HIGHADDR 0x00000000
#define XPAR_PLB_DEVICE_ID 0
#define XPAR_PLB_PLB_NUM_MASTERS 2


/******************************************************************/

/* Definitions for driver OPBARB */
#define XPAR_XOPBARB_NUM_INSTANCES 1

/* Definitions for peripheral OPB */
#define XPAR_OPB_BASEADDR 0xFFFFFFFF
#define XPAR_OPB_HIGHADDR 0x00000000
#define XPAR_OPB_DEVICE_ID 0
#define XPAR_OPB_NUM_MASTERS 1


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral LEDS_4BIT */
#define XPAR_LEDS_4BIT_BASEADDR 0x40020000
#define XPAR_LEDS_4BIT_HIGHADDR 0x4002FFFF
#define XPAR_LEDS_4BIT_DEVICE_ID 0
#define XPAR_LEDS_4BIT_INTERRUPT_PRESENT 0
#define XPAR_LEDS_4BIT_IS_DUAL 0


/* Definitions for peripheral PUSH_BUTTONS_4BIT */
#define XPAR_PUSH_BUTTONS_4BIT_BASEADDR 0x40000000
#define XPAR_PUSH_BUTTONS_4BIT_HIGHADDR 0x4000FFFF
#define XPAR_PUSH_BUTTONS_4BIT_DEVICE_ID 1
#define XPAR_PUSH_BUTTONS_4BIT_INTERRUPT_PRESENT 1
#define XPAR_PUSH_BUTTONS_4BIT_IS_DUAL 0


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral RS232 */
#define XPAR_RS232_BASEADDR 0x40600000
#define XPAR_RS232_HIGHADDR 0x4060FFFF
#define XPAR_RS232_DEVICE_ID 0
#define XPAR_RS232_BAUDRATE 57600
#define XPAR_RS232_USE_PARITY 0
#define XPAR_RS232_ODD_PARITY 0
#define XPAR_RS232_DATA_BITS 8


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 2
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral OPB_INTC_0 */
#define XPAR_OPB_INTC_0_BASEADDR 0x41200000
#define XPAR_OPB_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x00000000


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_OPB_TIMER_0_INTERRUPT_MASK 0X000001
#define XPAR_OPB_INTC_0_OPB_TIMER_0_INTERRUPT_INTR 0
#define XPAR_PUSH_BUTTONS_4BIT_IP2INTC_IRPT_MASK 0X000002
#define XPAR_OPB_INTC_0_PUSH_BUTTONS_4BIT_IP2INTC_IRPT_INTR 1

/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral OPB_TIMER_0 */
#define XPAR_OPB_TIMER_0_BASEADDR 0x41C00000
#define XPAR_OPB_TIMER_0_HIGHADDR 0x41C0FFFF
#define XPAR_OPB_TIMER_0_DEVICE_ID 0


/******************************************************************/


/* Definitions for peripheral PLB_BRAM_IF_CNTLR_1 */
#define XPAR_PLB_BRAM_IF_CNTLR_1_BASEADDR 0xfffe0000
#define XPAR_PLB_BRAM_IF_CNTLR_1_HIGHADDR 0xffffffff


/******************************************************************/


/* Definitions for peripheral DOCM_CNTLR */
#define XPAR_DOCM_CNTLR_BASEADDR 0x21800000
#define XPAR_DOCM_CNTLR_HIGHADDR 0x2180FFFF


/* Definitions for peripheral IOCM_CNTLR */
#define XPAR_IOCM_CNTLR_BASEADDR 0x00000000
#define XPAR_IOCM_CNTLR_HIGHADDR 0x0001FFFF


/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 200000000

/******************************************************************/

