
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.2.01 EDK_Im_Sp1.3
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xopbarb.h"

/*
* The configuration table for devices
*/

XOpbArb_Config XOpbArb_ConfigTable[] =
{
	{
		XPAR_OPB_DEVICE_ID,
		XPAR_OPB_BASEADDR,
		XPAR_OPB_NUM_MASTERS
	}
};


